#!/usr/bin/env python3
"""Generate style-matched opponent rationales for rationale-bearing conditions.

Reviewers 15bh, bbNu and egQr all ask what happens when the disagreeing expert
supplies a rationale, and specifically whether the evidence gate still lets
through *beneficial* revision when the disagreement genuinely adds information.

To answer that we need an opponent turn that argues for a given answer. We
The initial pass generates a two-sentence justification for BOTH admissible
answers of every item with one fixed generator, one template and T=0. Some
incorrect-target outputs were later regenerated by fix_opponent_rationales.py
with a different instruction and a retry loop. The stored quality field is a
shorthand for whether the assigned answer matches the benchmark label:

  * rationale assigned the ground-truth answer  -> "valid"
  * rationale assigned the other answer          -> "misleading"

At run time the opponent always contradicts Pass 1, so an item where Pass 1 was
wrong yields an argument in the correct answer direction, whereas an item where
Pass 1 was correct yields an argument in the incorrect direction. This label is
not an independent factual verification of every generated sentence.

Output: rebuttal/data/opponent_rationales.json
  {question_id: {"Yes": str, "No": str, "quality": {"Yes": "valid"|"misleading", ...}}}
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from tqdm import tqdm

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from client import Client  # noqa: E402

ITEMS = ROOT / "rebuttal" / "data" / "rebuttal_items.jsonl"
OUT = ROOT / "rebuttal" / "data" / "opponent_rationales.json"
GENERATOR = "openai/gpt-4o-mini"

SYSTEM = (
    "You write short justifications for a stated answer to an evidence-grounded "
    "Yes/No question. Write exactly two sentences. Refer to the excerpt. Do not "
    "mention that you were assigned the answer, do not hedge, and do not state "
    "that the answer might be wrong. Output only the two sentences."
)

TEMPLATE = (
    "Excerpt:\n{excerpt}\n\n"
    "Task:\n{prompt}\n\n"
    "Write a two-sentence justification for the answer \"{target}\"."
)

_lock = threading.Lock()


def load_items():
    return [json.loads(l) for l in ITEMS.open() if l.strip()]


def load_env(path: Path) -> None:
    if not path.exists():
        return
    for line in path.open():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


def one(item: dict, target: str, client: Client) -> tuple:
    excerpt = item["excerpt"]
    prompt = item["prompt_base"]
    msg = [
        {"role": "system", "content": SYSTEM},
        {"role": "user", "content": TEMPLATE.format(excerpt=excerpt, prompt=prompt, target=target)},
    ]
    r = client.chat(model=GENERATOR, messages=msg, temperature=0.0, max_tokens=180, top_p=1.0)
    text = (r.get("content") or "").strip().replace("\n", " ")
    return item["question_id"], target, text


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--max-workers", type=int, default=16)
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    load_env(ROOT / "backup.env")
    load_env(ROOT / ".env")
    items = load_items()
    if args.limit:
        items = items[: args.limit]

    out: dict = {}
    if OUT.exists():
        out = json.loads(OUT.read_text())

    tasks = [
        (it, t)
        for it in items
        for t in ("Yes", "No")
        if not (out.get(it["question_id"], {}).get(t))
    ]
    print(f"items={len(items)} rationales to generate={len(tasks)}")

    client = Client()
    with ThreadPoolExecutor(max_workers=args.max_workers) as ex:
        futs = [ex.submit(one, it, t, client) for it, t in tasks]
        for fut in tqdm(as_completed(futs), total=len(futs), desc="rationales"):
            try:
                qid, target, text = fut.result()
            except Exception as e:
                print(f"error: {e}")
                continue
            if not text:
                continue
            with _lock:
                out.setdefault(qid, {})[target] = text

    gt = {it["question_id"]: it["ground_truth"] for it in items}
    for qid, d in out.items():
        if qid in gt:
            d["quality"] = {
                t: ("valid" if t == gt[qid] else "misleading") for t in ("Yes", "No")
            }

    OUT.write_text(json.dumps(out, ensure_ascii=False, indent=1))
    complete = sum(1 for it in items if out.get(it["question_id"], {}).get("Yes")
                   and out.get(it["question_id"], {}).get("No"))
    print(f"Wrote {OUT}: {complete}/{len(items)} items with both rationales")


if __name__ == "__main__":
    main()
