#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BEAT-300 Benchmark Builder: Question Generation and Cognitive Boundary Filtering

This module implements the extreme quality control procedure for selecting
questions at the model's cognitive boundary (4:6 to 6:4 answer distribution).
Per DESIGN.md §4, N=300 items stratified as Medicine(100), Science(100), Law(100).
"""

import json
import hashlib
from typing import List, Dict, Any, Optional, Tuple
from pathlib import Path
from dataclasses import dataclass, asdict
import numpy as np
from collections import Counter
import re

try:
    import torch
except ImportError:
    torch = None

from src.data_structures import Question
from client import Client


@dataclass
class CandidateQuestion:
    """Candidate question before filtering"""
    source: str  # "PubMedQA", "SciFact", "ContractNLI"
    domain: str  # "Medicine", "Science", "Law"
    prompt_base: str  # Base prompt (no interventions)
    excerpt: str  # Native evidence excerpt
    ground_truth: str  # "Yes" or "No"
    metadata: Dict[str, Any]
    
    def to_question(self, question_id: str) -> Question:
        """Convert to Question object after selection"""
        return Question(
            question_id=question_id,
            domain=self.domain,
            prompt_base=self.prompt_base,
            excerpt=self.excerpt,
            metadata={
                **self.metadata,
                "source": self.source,
                "ground_truth": self.ground_truth
            }
        )


@dataclass
class BoundarySelectionResult:
    """Result from boundary selection for a candidate"""
    candidate_id: str
    model_id: str
    yes_count: int
    no_count: int
    refusal_count: int
    format_violation_count: int
    total_samples: int
    
    @property
    def valid_ratio(self) -> float:
        """Ratio of valid (non-refusal, non-violation) samples"""
        valid = self.yes_count + self.no_count
        return valid / self.total_samples if self.total_samples > 0 else 0.0
    
    @property
    def yes_proportion(self) -> float:
        """Proportion of Yes in valid samples"""
        valid = self.yes_count + self.no_count
        return self.yes_count / valid if valid > 0 else 0.0
    
    @property
    def is_in_boundary(self) -> bool:
        """Check if answer distribution is in [0.4, 0.6]"""
        yes_prop = self.yes_proportion
        return 0.4 <= yes_prop <= 0.6
    
    @property
    def is_high_quality(self) -> bool:
        """Check if question meets quality criteria"""
        # Valid ratio >= 80% (refusal/violation < 20%)
        # In boundary [0.4, 0.6]
        return self.valid_ratio >= 0.8 and self.is_in_boundary
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            **asdict(self),
            "valid_ratio": self.valid_ratio,
            "yes_proportion": self.yes_proportion,
            "is_in_boundary": self.is_in_boundary,
            "is_high_quality": self.is_high_quality
        }


def load_candidates_from_jsonl(candidates_file: Path) -> List[CandidateQuestion]:
    """
    Load candidate questions from JSONL file generated by collect_candidates.py.
    
    Expected format per DESIGN.md §3.2:
    {
        "candidate_id": "cand_XXXX",
        "domain": "Medicine" | "Science" | "Law",
        "prompt_base": "...",
        "excerpt": "...",
        "ground_truth": "Yes" | "No",
        "source": "PubMedQA" | "SciFact" | "ContractNLI",
        "hash": "...",
        "metadata": {...}
    }
    
    Args:
        candidates_file: Path to candidate_pool.jsonl
    
    Returns:
        List of CandidateQuestion objects
    """
    candidates = []
    
    with open(candidates_file, 'r', encoding='utf-8') as f:
        for line in f:
            if line.strip():
                data = json.loads(line)
                
                candidate = CandidateQuestion(
                    source=data["source"],
                    domain=data["domain"],
                    prompt_base=data["prompt_base"] if "prompt_base" in data else data.get("prompt", ""),
                    excerpt=data["excerpt"],
                    ground_truth=data["ground_truth"],
                    metadata=data.get("metadata", {})
                )
                candidates.append(candidate)
    
    return candidates


def parse_yesno_answer(response: str) -> Tuple[Optional[str], bool, bool]:
    """
    Parse Yes/No answer from model response.
    
    Returns:
        Tuple of (answer, is_refusal, is_format_violation)
        - answer: "Yes" or "No" or None
        - is_refusal: True if model refused to answer
        - is_format_violation: True if format is invalid
    """
    import re
    
    response_stripped = (response or "").strip()
    response_upper = response_stripped.upper()
    
    # Check for refusal patterns
    refusal_patterns = [
        r"I (?:CANNOT|CAN'T|SHOULDN'T) (?:ANSWER|PROVIDE|MAKE)",
        r"(?:UNABLE|IMPOSSIBLE) TO (?:ANSWER|DETERMINE|DECIDE)",
        r"I DON'T HAVE (?:ENOUGH|SUFFICIENT) INFORMATION",
        r"CANNOT BE (?:DETERMINED|ANSWERED)",
        r"I (?:MUST|NEED TO) DECLINE"
    ]
    
    for pattern in refusal_patterns:
        if re.search(pattern, response_upper):
            return None, True, False
    
    # Output contract for screening: first line must be Yes or No
    first_line = response_stripped.splitlines()[0].strip().upper() if response_stripped else ""
    if first_line == "YES":
        return "Yes", False, False
    if first_line == "NO":
        return "No", False, False

    return None, False, True


def sample_api_responses(
    client: Client,
    model_id: str,
    prompt: str,
    excerpt: str,
    num_samples: int = 10,
    temperature: float = 0.7,
    max_tokens: int = 120,
    stop: Optional[List[str]] = None,
) -> List[str]:
    """
    Sample multiple responses from an API model (OpenRouter) for boundary selection.
    """
    responses: List[str] = []
    full_input = f"Evidence Excerpt:\n\n{excerpt}\n\n---\n\n{prompt}"
    messages = [{"role": "user", "content": full_input}]

    for _ in range(num_samples):
        resp = client.chat(
            model=model_id,
            messages=messages,
            temperature=temperature,
            top_p=1.0,
            max_tokens=max_tokens,
            stop=stop,
        )
        responses.append(resp.get("content", ""))

    return responses


def sample_model_responses(
    model,
    tokenizer,
    prompt: str,
    excerpt: str,
    num_samples: int = 10,
    temperature: float = 0.7,
    max_tokens: int = 120,
    device: str = "cuda"
) -> List[str]:
    """
    Sample multiple responses from a model for boundary selection.
    
    Per DESIGN.md §3.2: All questions include a native evidence excerpt.
    The full input includes both the question and the excerpt.
    
    Args:
        model: Loaded model
        tokenizer: Tokenizer
        prompt: Question prompt
        excerpt: Native evidence excerpt
        num_samples: Number of independent samples
        temperature: Sampling temperature
        max_tokens: Max generation length
        device: Device
    
    Returns:
        List of response strings
    """
    responses = []
    
    # Construct full input with excerpt
    full_input = f"Evidence Excerpt:\n\n{excerpt}\n\n---\n\n{prompt}"
    
    messages = [
        {"role": "user", "content": full_input}
    ]
    
    # Apply chat template if available
    if hasattr(tokenizer, 'apply_chat_template'):
        formatted_prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    else:
        formatted_prompt = full_input
    
    inputs = tokenizer(formatted_prompt, return_tensors="pt").to(device)
    
    for _ in range(num_samples):
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=max_tokens,
                temperature=temperature,
                do_sample=True,
                top_p=1.0,
                num_return_sequences=1
            )
        
        response = tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)
        responses.append(response)
    
    return responses


def evaluate_candidate_boundary_local(
    candidate: CandidateQuestion,
    model,
    tokenizer,
    num_samples: int = 10,
    temperature: float = 0.7,
    device: str = "cuda"
) -> BoundarySelectionResult:
    """
    Evaluate a candidate question on cognitive boundary.
    
    Args:
        candidate: Candidate question (with evidence excerpt)
        model: Loaded screening model
        tokenizer: Tokenizer
        num_samples: Number of samples per candidate
        temperature: Sampling temperature
        device: Device
    
    Returns:
        BoundarySelectionResult with answer distribution
    """
    import torch
    
    responses = sample_model_responses(
        model, tokenizer, candidate.prompt_base, candidate.excerpt,
        num_samples, temperature, device=device
    )
    
    yes_count = 0
    no_count = 0
    refusal_count = 0
    violation_count = 0
    
    for response in responses:
        answer, is_refusal, is_violation = parse_yesno_answer(response)
        
        if is_refusal:
            refusal_count += 1
        elif is_violation:
            violation_count += 1
        elif answer == "Yes":
            yes_count += 1
        elif answer == "No":
            no_count += 1
    
    model_id = model.config._name_or_path if hasattr(model.config, '_name_or_path') else "unknown"
    
    # Use combined prompt+excerpt for hash
    combined = f"{candidate.prompt_base}|{candidate.excerpt}"
    
    return BoundarySelectionResult(
        candidate_id=hashlib.md5(combined.encode()).hexdigest()[:8],
        model_id=model_id,
        yes_count=yes_count,
        no_count=no_count,
        refusal_count=refusal_count,
        format_violation_count=violation_count,
        total_samples=num_samples
    )


def evaluate_candidate_boundary_api(
    candidate: CandidateQuestion,
    client: Client,
    model_id: str,
    num_samples: int = 10,
    temperature: float = 0.7,
    max_tokens: int = 120,
    stop: Optional[List[str]] = None,
) -> BoundarySelectionResult:
    """
    Evaluate a candidate question on cognitive boundary for an API model.
    """
    responses = sample_api_responses(
        client=client,
        model_id=model_id,
        prompt=candidate.prompt_base,
        excerpt=candidate.excerpt,
        num_samples=num_samples,
        temperature=temperature,
        max_tokens=max_tokens,
        stop=stop,
    )

    yes_count = 0
    no_count = 0
    refusal_count = 0
    violation_count = 0

    for response in responses:
        answer, is_refusal, is_violation = parse_yesno_answer(response)
        if is_refusal:
            refusal_count += 1
        elif is_violation:
            violation_count += 1
        elif answer == "Yes":
            yes_count += 1
        elif answer == "No":
            no_count += 1

    combined = f"{candidate.prompt_base}|{candidate.excerpt}"
    return BoundarySelectionResult(
        candidate_id=hashlib.md5(combined.encode()).hexdigest()[:8],
        model_id=model_id,
        yes_count=yes_count,
        no_count=no_count,
        refusal_count=refusal_count,
        format_violation_count=violation_count,
        total_samples=num_samples,
    )


def select_beat300_questions(
    candidates: List[CandidateQuestion],
    screening_models: List[Dict[str, Any]],  # [{"type": "local"/"openrouter", ...}]
    num_samples: int = 10,
    temperature: float = 0.7,
    target_count: int = 300,
    device: str = "cuda",
    log_file: Optional[Path] = None,
    stop_sequences: Optional[List[str]] = None,
    max_tokens: int = 120,
    domain_targets: Optional[Dict[str, int]] = None
) -> Tuple[List[Question], List[Dict[str, Any]]]:
    """
    Select BEAT-300 questions from candidates using boundary filtering.
    
    Selection criteria (DESIGN.md §4.3):
    1. For at least one screening model: answer distribution in [0.4, 0.6]
    2. For no screening model: degenerate distribution (all same answer)
    3. Refusal/violation rate < 20%
    4. Stable parsing
    
    Args:
        candidates: List of candidate questions
        screening_models: List of screening model specs
        num_samples: Samples per candidate
        temperature: Sampling temperature
        target_count: Target number of questions (default: 300)
        device: Device
        log_file: Optional path to save selection log
    
    Returns:
        Tuple of (selected_questions, selection_log)
    """
    if stop_sequences is None:
        stop_sequences = ["</s>", "###", "User:", "Assistant:", "Q:", "A:", "B:"]

    if domain_targets is None:
        domain_targets = {"Medicine": 100, "Science": 100, "Law": 100}

    print(f"Starting BEAT-300 selection from {len(candidates)} candidates")
    print(f"Screening with {len(screening_models)} model(s)")
    
    selection_log = []
    
    for i, candidate in enumerate(candidates):
        print(f"\n[{i+1}/{len(candidates)}] Evaluating candidate: {candidate.source}")
        
        combined = f"{candidate.prompt_base}|{candidate.excerpt}"
        candidate_log = {
            "candidate_id": hashlib.md5(combined.encode()).hexdigest()[:8],
            "prompt_hash": hashlib.sha256(candidate.prompt_base.encode("utf-8")).hexdigest()[:16],
            "excerpt_hash": hashlib.sha256(candidate.excerpt.encode("utf-8")).hexdigest()[:16],
            "source": candidate.source,
            "domain": candidate.domain,
            "prompt_base": candidate.prompt_base,
            "excerpt": candidate.excerpt[:200] + "..." if len(candidate.excerpt) > 200 else candidate.excerpt,
            "ground_truth": candidate.ground_truth,
            "screening_results": []
        }
        
        has_boundary = False
        has_degenerate = False
        all_high_quality = True
        
        for spec in screening_models:
            if spec.get("type") == "local":
                result = evaluate_candidate_boundary_local(
                    candidate,
                    spec["model"],
                    spec["tokenizer"],
                    num_samples=num_samples,
                    temperature=temperature,
                    device=device,
                )
            elif spec.get("type") == "openrouter":
                result = evaluate_candidate_boundary_api(
                    candidate,
                    spec["client"],
                    spec["model_id"],
                    num_samples=num_samples,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    stop=stop_sequences,
                )
            else:
                raise ValueError(f"Unknown screening model type: {spec.get('type')}")
            
            candidate_log["screening_results"].append(result.to_dict())
            
            print(f"  Model: {result.model_id}")
            print(f"    Yes/No: {result.yes_count}/{result.no_count}")
            print(f"    Yes prop: {result.yes_proportion:.2f}")
            print(f"    In boundary: {result.is_in_boundary}")
            print(f"    High quality: {result.is_high_quality}")
            
            if result.is_in_boundary:
                has_boundary = True
            
            if result.yes_proportion in [0.0, 1.0]:
                has_degenerate = True
            
            if not result.is_high_quality and result.valid_ratio < 0.8:
                all_high_quality = False
        
        # Decision: retain if has_boundary and not degenerate and quality OK
        retain = has_boundary and not has_degenerate and all_high_quality
        candidate_log["retained"] = retain
        
        print(f"  Decision: {'RETAIN' if retain else 'REJECT'}")
        
        selection_log.append(candidate_log)
        
        # Do NOT early-stop: need full pool for stratified sampling (DESIGN.md §3.3)
    
    # Stratified sampling to BEAT-300 (DESIGN.md §4.4)
    retained_candidates: List[Tuple[CandidateQuestion, Dict[str, Any]]] = []
    for idx, log_entry in enumerate(selection_log):
        if log_entry.get("retained"):
            retained_candidates.append((candidates[idx], log_entry))

    # Compute entropy proxy per candidate using the most boundary-like screening result
    def _entropy_from_counts(yes_c: int, no_c: int) -> float:
        total = yes_c + no_c
        if total <= 0:
            return 0.0
        p = yes_c / total
        q = no_c / total
        ent = 0.0
        if p > 0:
            ent -= p * np.log2(p)
        if q > 0:
            ent -= q * np.log2(q)
        return float(ent)

    by_domain: Dict[str, List[Tuple[CandidateQuestion, float, float]]] = {"Medicine": [], "Science": [], "Law": []}
    for cand, log_entry in retained_candidates:
        # pick max entropy across screening models
        ent = 0.0
        best_dist = 1.0
        for r in log_entry.get("screening_results", []):
            yes_c = int(r.get("yes_count", 0))
            no_c = int(r.get("no_count", 0))
            ent = max(ent, _entropy_from_counts(yes_c, no_c))
            total = yes_c + no_c
            if total > 0:
                p_yes = yes_c / total
                best_dist = min(best_dist, abs(p_yes - 0.5))
        if cand.domain in by_domain:
            by_domain[cand.domain].append((cand, ent, best_dist))

    # Select per-domain targets, difficulty-balanced via entropy bins (DESIGN.md §3.3)
    # Bin heuristic: near 5/5 if |p_yes - 0.5| <= 0.05 else near 6/4.
    selected_questions: List[Question] = []
    selected_id_map: Dict[str, str] = {}  # candidate_id -> question_id
    for domain, target_n in domain_targets.items():
        pool_all = by_domain.get(domain, [])
        high_entropy = sorted([x for x in pool_all if x[2] <= 0.05], key=lambda x: x[1], reverse=True)
        low_entropy = sorted([x for x in pool_all if x[2] > 0.05], key=lambda x: x[1], reverse=True)
        pool = high_entropy + low_entropy
        if len(pool) < target_n:
            raise ValueError(f"Not enough retained candidates for domain={domain}: have {len(pool)}, need {target_n}")

        half = target_n // 2
        chosen: List[CandidateQuestion] = []
        for cand, _ent, _dist in high_entropy[:half]:
            chosen.append(cand)
        for cand, _ent, _dist in low_entropy[: (target_n - len(chosen))]:
            chosen.append(cand)
        # If one bin is short, top up from the other bin
        if len(chosen) < target_n:
            remaining = [c for c, _e, _d in pool if c not in chosen]
            chosen.extend(remaining[: (target_n - len(chosen))])

        for cand in chosen:
            question_id = f"q{len(selected_questions)+1:03d}"
            cand_id = hashlib.md5(f"{cand.prompt_base}|{cand.excerpt}".encode()).hexdigest()[:8]
            selected_id_map[cand_id] = question_id
            selected_questions.append(cand.to_question(question_id))
    
    print(f"\n{'='*60}")
    print(f"BEAT-300 Selection Complete")
    print(f"Total candidates: {len(candidates)}")
    print(f"Questions retained: {len(selected_questions)}")
    print(f"{'='*60}")
    
    # Save selection log (JSONL) if requested (DESIGN.md §3.3)
    # Annotate selection log entries with final question_id for traceability
    for entry in selection_log:
        cid = entry.get("candidate_id", "")
        if cid in selected_id_map:
            entry["selected_question_id"] = selected_id_map[cid]

    if log_file:
        log_file.parent.mkdir(parents=True, exist_ok=True)
        with open(log_file, "w", encoding="utf-8") as f:
            meta = {
                "record_type": "meta",
                "total_candidates": len(candidates),
                "num_samples": num_samples,
                "temperature": temperature,
                "stop_sequences": stop_sequences,
                "domain_targets": domain_targets,
                "screening_models": [
                    ({"type": "local", "model_id": s.get("model_id", "local")} if s.get("type") == "local"
                     else {"type": "openrouter", "model_id": s.get("model_id", "")})
                    for s in screening_models
                ],
            }
            f.write(json.dumps(meta, ensure_ascii=False) + "\n")
            for entry in selection_log:
                entry_out = {"record_type": "candidate", **entry}
                f.write(json.dumps(entry_out, ensure_ascii=False) + "\n")
        print(f"Selection log saved to: {log_file}")
    
    return selected_questions, selection_log


def save_beat300_questions_minimal(questions: List[Question], output_file: Path) -> None:
    """
    Save frozen BEAT-300 questions.

    Required keys (DESIGN.md §4.4): {question_id, domain, prompt_base, excerpt, hash}
    We also include a minimal `metadata` payload needed to instantiate B2/B3 add-ons
    during experiments (e.g., `b2_evidence`, `source`, and `ground_truth`).
    """
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "w", encoding="utf-8") as f:
        for q in questions:
            meta = q.metadata or {}
            # Keep only fields needed for experiment instantiation/auditability
            metadata_keep = {
                "source": meta.get("source"),
                "ground_truth": meta.get("ground_truth"),
                "b2_evidence": meta.get("b2_evidence"),
                "doc_id": meta.get("doc_id"),
                "pubmed_id": meta.get("pubmed_id"),
                "original_label": meta.get("original_label"),
            }
            rec = {
                "question_id": q.question_id,
                "domain": q.domain,
                "prompt_base": q.prompt_base,
                "excerpt": q.excerpt,
                "hash": q.hash,
                "metadata": {k: v for k, v in metadata_keep.items() if v is not None},
            }
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")


def main():
    import argparse

    parser = argparse.ArgumentParser(description="BEAT-300 boundary selection (DESIGN.md §4.3)")
    parser.add_argument("--candidates", type=str, required=True, help="Path to data/candidate_pool.jsonl")
    parser.add_argument("--output", type=str, default="frozen_artifacts/beat300_questions.jsonl")
    parser.add_argument("--selection-log", type=str, default="frozen_artifacts/selection_log.jsonl")
    parser.add_argument("--screening-models", type=str, nargs="+", default=["meta-llama/Llama-3.1-8B-Instruct", "Qwen/Qwen2.5-7B-Instruct"])
    parser.add_argument("--num-samples", type=int, default=10)
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--max-tokens", type=int, default=120)
    parser.add_argument("--device", type=str, default="cuda")
    parser.add_argument("--target-count", type=int, default=300)
    args = parser.parse_args()

    candidates = load_candidates_from_jsonl(Path(args.candidates))

    # Build screening specs
    specs: List[Dict[str, Any]] = []
    for mid in args.screening_models:
        if mid.startswith(("openai/", "anthropic/", "google/", "mistralai/")):
            client = Client()
            specs.append({"type": "openrouter", "model_id": mid, "client": client})
        else:
            if torch is None:
                raise RuntimeError("torch is required for local screening models")
            try:
                from transformers import AutoTokenizer, AutoModelForCausalLM
            except Exception as e:
                raise RuntimeError("transformers is required for local screening models") from e
            tok = AutoTokenizer.from_pretrained(mid)
            mdl = AutoModelForCausalLM.from_pretrained(
                mid,
                torch_dtype=torch.float16 if args.device == "cuda" else torch.float32,
                device_map="auto" if args.device == "cuda" else None,
            )
            mdl.eval()
            specs.append({"type": "local", "model_id": mid, "model": mdl, "tokenizer": tok})

    # Domain targets: enforce 100/100/100 when target_count=300; else proportional
    if args.target_count == 300:
        domain_targets = {"Medicine": 100, "Science": 100, "Law": 100}
    else:
        per = args.target_count // 3
        domain_targets = {"Medicine": per, "Science": per, "Law": args.target_count - 2 * per}

    selected, _log = select_beat300_questions(
        candidates=candidates,
        screening_models=specs,
        num_samples=args.num_samples,
        temperature=args.temperature,
        target_count=args.target_count,
        device=args.device,
        log_file=Path(args.selection_log),
        stop_sequences=["</s>", "###", "User:", "Assistant:", "Q:", "A:", "B:"],
        max_tokens=args.max_tokens,
        domain_targets=domain_targets,
    )

    save_beat300_questions_minimal(selected, Path(args.output))
    print(f"Saved BEAT-300 questions to: {args.output}")


if __name__ == "__main__":
    main()

